language: python
sudo: false
branches:
  only:
    - master
    - example_updates
python:
  - 3.6
  - 3.7

# to add testing, replace PACKAGE_NAME with your package's name, and {AUTHOR_EMAILS} with a
# YAML list of author emails, like:
# - robert@gmail.com
# - betsy@gmail.com
# - frank@gmail.com

env:
  - PYSAL_PYPI=true MPLBACKEND='pdf'
  - PYSAL_PYPI=false MPLBACKEND='pdf'

matrix:
  allow_failures: #allow travis tests to fail if using the github version of libpysal
      - python: 3.5
        env: PYSAL_PYPI=false MPLBACKEND='pdf'
      - python: 3.6
        env: PYSAL_PYPI=false MPLBACKEND='pdf'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -y -q --override-channels -c conda-forge -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes --file requirements.txt
  - conda install --yes geopandas #comment this line if geopandas is not a dependency for the package
  - pip install -r requirements_tests.txt
  # configure dual tests (for dependency libpysal)
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
        else echo 'testing git libpysal'; git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../;
    fi;

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=access

notifications:
    email:
        recipients:
            {AUTHOR_EMAILS}
        on_success: change
        on_failure: always

after_success:
  - coveralls

