---
name: Build Docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: Manual Doc Build
        default: run-doc-build
        required: false

jobs:
  docs:
    name: CI (${{ matrix.os }}-${{ matrix.environment-file }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: ['ubuntu-latest']
        environment-file: [py313_latest]
        experimental: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
           miniconda-version: 'latest'
           auto-update-conda: true
           auto-activate-base: false
           environment-file: .ci/ ${{ matrix.environment-file }} .yaml
           activate-environment: test
      - shell: bash -l {0}
        run: conda info --all
      - shell: bash -l {0}
        run: conda list
      - shell: bash -l {0}
        run: conda config --show-sources
      - shell: bash -l {0}
        run: conda config --show
      - shell: bash -l {0}
        run: pip install -e . --no-deps --force-reinstall
      - shell: bash -l {0}
        run: cd docs; make html
      - name: Commit documentation changes
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           branch: gh-pages
           directory: gh-pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
           force: true
